---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  # Add details for ecr at AWS
  ecr-docker:
    type: docker-registry
    url: https://public.ecr.aws
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Add this section for each directory with a Dockerfile, K8s manifest, or Helm chart
  # They must use a semver tag, and Dependabot must be able to access the registry
  # You can give it access to private ones:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-private-registries
  # follow along on a feature request to support multiple directories in one package-ecosystem
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[Docker] "
      prefix: "[Docker] "
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[Docker 28mm] "
      prefix: "[Docker 28mm] "
    # Raise pull requests for version updates
    # to docker against the `28mm` branch
    target-branch: "28mm"
    ## Labels from defined list on pull requests for version updates only
    #labels:
    #  - "Docker dependencies for 28mm"
    # Allow up to 2 open pull requests for Docker dependencies in 28mm - This may be for all docker package systems
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[Docker PirateWeather] "
      prefix: "[Docker PirateWeather] "
    # Raise pull requests for version updates
    # to docker against the `PirateWeather` branch
    target-branch: "PirateWeather"
    ## Labels from defined list on pull requests for version updates only
    #labels:
    #  - "Docker dependencies for PirateWeather" 
    # Allow up to 2 open pull requests for Docker dependencies in PirateWeather - This may be for all docker package systems
    open-pull-requests-limit: 10
